spring.application.name=aeropure_backend
spring.datasource.url=jdbc:postgresql://localhost:5432/aeropure
spring.datasource.username=postgres
spring.datasource.password=kundi999
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8001